config/routes.rb
Rails.application.routes.draw do

  resources :photos
  resources :suppliers do
    resources :supplies, only: [:new, :create, :edit, :update, :delete, :destroy]
    resources :bundle_supplies, only: [:new, :create]
    collection do 
      get 'get_pricing_model'
      get 'login'
      get 'get_session_user'
      post 'login_attempt'
      delete 'logout'
    end
  end
  root to: 'suppliers#login'

end

app/models/bundle.rb
class Bundle < ActiveRecord::Base
	has_many :bundles_supplies
	has_many :supplies, through: :bundles_supplies
end

app/models/bundle_supply.rb
class BundleSupply < ActiveRecord::Base
	belongs_to :bundle
	belongs_to :supply
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :supply
	belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_many :supplies, through: :galleries
	has_many :galleries
	mount_uploader :avatar, AvatarUploader
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_secure_password
	attr_accessor :login_email, :login_password
	has_many :supplies
	has_many :photos, through: :galleries
	has_many :galleries
	mount_uploader :avatar, AvatarUploader


	validates :supplier_name, presence: true
	validates :supplier_address, presence: true
	validates :supplier_contact_no, presence: true
	validates :supplier_email, presence: true
	validates :supplier_desc, presence: true
	validates :password, presence: true
end

app/models/supply.rb
class Supply < ActiveRecord::Base
	belongs_to :supplier
	has_many :bundle_supplies
	has_many :bundles, through: :bundle_supplies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  def set_access_control_headers
    logger.info request.headers['Origin']
    headers['Access-Control-Allow-Origin'] = request.headers['Origin']
    headers['Access-Control-Allow-Methods'] = 'POST,GET,OPTIONS, PUT, DELETE'
    headers['Access-Control-Request-Method'] = '*'    
    headers['Access-Control-Allow-Credentials'] = 'true'
    headers['Access-Control-Max-Age'] = '1728000'
  end

  private

   def current_user
      @current_user ||= Supplier.find(session[:user_id]) if session[:user_id]
   end

   helper_method :current_user

   def authenticate_user
      if session[:user_id]
        @current_user ||= Supplier.find(session[:user_id])
        return true
      else
        redirect_to(:controller => 'suppliers', :action => 'login')
        return false
      end
   end

   def save_login_state
      if session[:user_id] 
        redirect_to(:controller => 'suppliers', :action => 'index')
        return false
      else
        return true
      end
  end

end

app/controllers/bundle_supplies_controller.rb
class BundleSuppliesController < ApplicationController

	def create
		puts "****#{params}****"
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def new
		@photo = Photo.new
	end

	def create
	    @clearance = Photo.create(clearance_params)
  	end

  	 def edit
	    @clearance = Clearance.find(params[:id])
	 end

	  def update
	    @clearance = Clearance.find(params[:id])
	    if @clearance.update_attributes(params[:clearance])
	      redirect_to clearances_url, notice: "Clearance was successfully updated."
	    else
	      render :edit
	    end
	  end

	  def destroy
	    @clearance = Clearance.find(params[:id])
	    @clearance.destroy
	    redirect_to clearances_url, notice: "Clearance was successfully destroyed."
	  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
	before_action :authenticate_user, only: [:index]
	before_action :save_login_state, only: [:login, :login_attempt]

	def index
		@supplier = Supplier.find(current_user)
		@supply = @supplier.supplies
	end

	def new
		@supplier = Supplier.new
	end

	def create
		@supplier = Supplier.new(supplier_params)

		respond_to do |format|
			if @supplier.save
				format.html { redirect_to @supplier, notice: 'Successfully Created!' }
				format.js
			else
				puts "***you are here******"
				format.html { render 'new' }
				format.js
			end
		end
	end

	def login
	end

	def login_attempt
		supplier = Supplier.find_by_supplier_email(params[:supplier][:login_email])

		respond_to do |format|
		    if supplier && supplier.authenticate(params[:supplier][:login_password])
		      session[:user_id] = supplier.id
		      format.html { redirect_to suppliers_url }
		      #format.js { render json: supplier, status: :ok }
		    else
		      format.html { render 'login', notice: 'Invalid email/password combination' }
		      format.js
		    end
		end
	end

	def get_pricing_model
		pricing = Pricing.all

		respond_to do |format|
			if pricing
				format.js { render json: pricing, status: :ok }
			end
		end
	end

	def get_session_user
		session_user = Supplier.find(current_user)

		respond_to do |format|
			if session_user
				format.js { render json: session_user, status: :ok }
			end
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to login_suppliers_url
	end

	private

	def supplier_params
		params.require(:supplier).permit(:supplier_name, :supplier_desc, :supplier_address, :supplier_contact_no, :supplier_email, :password, :avatar)
	end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController

	def new
		@supplier = Supplier.find(params[:supplier_id])
		@supply = Supply.new
		supplies = @supplier.supplies

		respond_to do |format|
			if supplies
				format.js { render json: supplies, status: :ok}
			end
		end
	end

	def create
		@supplier = Supplier.find(params[:supplier_id])
		@supply = @supplier.supplies.new(supply_params)

		respond_to do |format|
			if @supply.save
				format.html { redirect_to suppliers_url, notice: "New Supply Created! "}
				format.js
			else
				format.html { render 'new' }
				format.js
			end
		end
	end

	private

	def supply_params
		params.require(:supply).permit(:supply_name, :pricing, :supply_price, :supply_desc)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bundle_supplies_helper.rb
module BundleSuppliesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="vendormine">
<head>
  <title>Vendormine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-controller='appController'>
<div class="supplier-container">
	<div class="row sidebar-nav-fixed affix">
		<div class="col-md-12 panel panel-default">
			<% if current_user %>
			    <div class="row avatar-panel">
			    	<div class="row">
				    	<div class="col-md-2"></div>
						<div class="col-md-8">
							<img src="http://placekitten.com/g/150/150" alt="..." class="img-circle img-responsive">
						</div>
						<div class="col-md-2"></div>
					</div>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-8 current-user">
							<p class="supplier-name"><%= current_user.supplier_name %></p>
						</div>
						<div class="col-md-2"></div>
					</div>
			    </div>
				<div class="row nav-bar">
					<ul class="nav nav-pills nav-stacked">
						<li class="active"><a href="#">Home</a></li>
					    <li><a href="#">Account</a></li>
					    <li><%= link_to "Add Supply", new_supplier_supply_path(current_user) %></li>
					    <li><%= link_to "Logout", logout_suppliers_path, method: :delete %></li>
					</ul>
				</div>
			<% else %>

			<% end %>
		</div>
	</div>
</div>

<!-- <div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar-nav-fixed affix">
                <div class="well">
                    <ul class="nav ">
                        <li class="nav-header">Sidebar</li>
                        <li class="active"><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li class="nav-header">Sidebar</li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li class="nav-header">Sidebar</li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                        <li><a href="#">Link</a>
                        </li>
                    </ul>
                </div>
                /.well
            </div>
            /sidebar-nav-fixed
        </div>
    </div>
</div> -->
<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<%= form_for Photos.new do |f| %>
	<%= f.label :avatar, "Clearances" %>
	<%= f.file_field :avatar, multiple: true, name: "clearance[avatar]" %> 
<% end %>

app/views/suppliers/index.html.erb
<!-- <div supply-panel>
  
</div> -->
<div class="col-md-9 content-container">
	<div class="row">
		<h2 class="supply-header">Supply</h2>
		<div class="col-md-12">
			<table class="table table-bordered">
	        <thead>
	          <tr>
	            <th>Supply Name</th>
	            <th>Pricing model</th>
	            <th>Price</th>
	            <th>Description</th>
	            <th>Action</th>
	          </tr>
	        </thead>
	        <tbody>
	        <% @supply.each do |s| %>
	          <tr>
	            <td><%= s.supply_name %></td>
	            <td><%= s.pricing %></td>
	            <td>PHP <%= s.supply_price %></td>
	            <td><%= s.supply_desc %></td>
	            <td><a href="#" class="btn btn-default">Set Gallery</a>
	            	<%= link_to 'Edit', edit_supplier_supply_path(current_user, @supply), class: "btn btn-info" %>
	        <a href="#" class="btn btn-danger">Remove</a></td>
	          </tr>
	        <% end %>
	        </tbody>
	      </table>
      </div>
	</div>

	<div class="row">
		<h2 class="supply-header pull-left">Bundle</h2>
		<!-- <a href="#" class="pull-right btn btn-warning pull-bottom">Add Bundle</a> -->
		<div bundle-panel>
			
		</div>
		<div class="col-md-12">
			<table class="table table-bordered">
	        <thead>
	          <tr>
	            <th>Supply Name</th>
	            <th>Pricing model</th>
	            <th>Price</th>
	            <th>Description</th>
	            <th>Action</th>
	          </tr>
	        </thead>
	        <tbody>
	        <% @supply.each do |s| %>
	          <tr>
	            <td><%= s.supply_name %></td>
	            <td><%= s.pricing %></td>
	            <td>PHP <%= s.supply_price %></td>
	            <td><%= s.supply_desc %></td>
	            <td><a href="#" class="btn btn-default">Set Gallery</a>
	            	<%= link_to 'Edit', edit_supplier_supply_path(current_user, @supply), class: "btn btn-info" %>
	        <a href="#" class="btn btn-danger">Remove</a></td>
	          </tr>
	        <% end %>
	        </tbody>
	      </table>
      </div>
	</div>
</div>

app/views/suppliers/login.html.erb
<div class="col-md-4"></div>
<div class="col-md-4" ng-controller='appController'>
		 <%= form_for(:supplier, url: 'login_attempt') do |f| %>
	      <div class="form-group">
	        <label class="client-login-label">Email</label>
	        <%= f.email_field(:login_email, class: 'form-control client-login-field', required: true, placeholder: 'Username or Email') %>
	      </div>
	       <div class="form-group">
	        <label class="client-login-label">Password</label>
	        <%= f.password_field(:login_password, class: 'form-control client-login-field', required: true, placeholder: 'Password') %>
	      </div>
	      <div class="form-group">
	      	<%= f.submit "Log In", class: 'btn btn-lg btn-success' %>
	      </div>
		<% end %>
</div>
<div class="col-md-4"> {{ user }}</div>

app/views/suppliers/new.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
  <%= form_for @supplier do |f| %>
    <div class="row">
     <div class="col-md-3"></div>
     <div class="fileinput fileinput-new col-md-6" data-provides="fileinput">
       <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
         <img src="http://placekitten.com/g/200/150" alt="...">
       </div>
       <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
       <div class="row">
         <div class="col-md-2"></div>
         <div class="col-md-8">
           <span class="btn btn-success btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
         </div>
         <div class="col-md-2"></div>
       </div>
     </div>
     <div class="col-md-3"></div>
    </div>
    <hr>
    <div class="form-group">
      <label for="exampleInputEmail1">Company Name</label>
      <%= f.text_field :supplier_name, class: 'form-control' , placeholder: 'Comapny Name' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Email</label>
      <%= f.text_field :supplier_email, class: 'form-control' , placeholder: 'Comapny Email' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <%= f.password_field :password, class: 'form-control' , placeholder: 'Password' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Address</label>
      <%= f.text_field :supplier_address, class: 'form-control' , placeholder: 'Comapny Address' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Contact no</label>
      <%= f.text_field :supplier_contact_no, class: 'form-control' , placeholder: 'Comapny Contact Number' %>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Description</label>
      <%= f.text_area :supplier_desc, class: 'form-control' , placeholder: 'Comapny Description' %>
    </div>
    <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>

  <% end %>
</div>
<div class="col-md-4"></div>

app/views/supplies/new.html.erb
<div class="col-md-9 content-container">
  <div class="row add-supply">
    <div class="row">
      <div class="col-md-6 new-supply">
        <h2>New Supply</h2>
      </div>
    </div>

    <div class="row">
    <div class="col-md-6">
      <%= form_for [@supplier,@supply] do |f| %>
        <div class="form-group">
          <label for="exampleInputEmail1">Supply name</label>
          <%= f.text_field :supply_name, class:'form-control' %>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Pricing model</label>
          <%= f.select :pricing, %w{ Per-Hour Per-Pax Fixed-Rate }, class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Supply Price</label>
          <%= f.text_field :supply_price, class:'form-control' %>
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">Description</label>
          <%= f.text_area :supply_desc, class:'form-control', rows:'5' %>
        </div>
        <%= f.submit "Add Supply", class: 'btn btn-lg btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>